# Rhythm Factory - Poste sua música, crie seu ritmo.
# Copyright (C) 2025 Cleverton Santiago
#
# Este programa é licenciado sob a GNU GPLv3. 
# Para mais detalhes, veja o arquivo LICENSE no repositório ou <https://www.gnu.org/licenses/>.

open_collective:    rhythm_factory
ko_fi:              Rhythm_Factory
